version: '2'
services:
  hadoop-master:
    hostname: hadoop-master
    image: 'teradatalabs/cdh5-hive'
    ports:
      - '8020:8020'
      - '8088:8088'
      - '9083:9083'
      - '10000:10000'
      - '50070:50070'
      - '50075:50075'

  presto-master:
    hostname: presto-master
    build: 'presto-dev-env'
    image: 'teradatalabs/presto-dev-env-distributed'
    ports: 
      - '8080:8080'
    depends_on:
      - 'hadoop-master'
    command: /presto-launcher-wrapper.sh master run
    volumes:
      - ../../../presto-server/target/:/presto-server/target:ro
    env_file:
        - ../../target/classes/presto.env

  presto-worker:
    image: 'teradatalabs/presto-dev-env-distributed'
    depends_on:
      - 'presto-master'
    command: /presto-launcher-wrapper.sh worker run
    volumes_from: 
      - presto-master
    env_file:
        - ../../target/classes/presto.env
